### PR TITLE
Xcode 13 produces error `Cannot find type 'SnippetBuilder'` in scope

### PR DESCRIPTION
**Pull request by sofiaromorales**
Bug/issue #, if applicable: #36 

## Summary

Fix for bug introduced in https://github.com/apple/swift-docc-plugin/commit/5f2e247f5efef4ff8ee603443a9a29225ce9f0e2 refactor, where `SnippetBuilder` had to be refactored to `SnippetExtractor`.

## Dependencies

N/A

## Testing

N/A

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Review by ethan-kusters — APPROVED** [review]

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by ethan-kusters** [comment]
Thank you @sofiaromorales!
